I4G005448SK2_src/I4G005448SK2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]

I4G005448SK2_src/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.PostListView.as_view(), name="all"),
    path("create/", views.PostCreateView.as_view(), name="post_create"),
    path("delete/<slug:slug>", views.PostDeleteView.as_view(), name="post_delete"),
    path("update/<slug:slug>", views.PostUpdateView.as_view(), name="post_update"),
    path("read/<slug:slug>", views.PostDetailView.as_view(), name="post_detail"),
]

I4G005448SK2_src/blog/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.urls import reverse
from django.template.defaultfilters import slugify
# Create your models here.


class Post(models.Model):

    STATUS_CHOICES = (
        ("draft", "Draft"),
        ("published", "Published")
    )

    # DB Fields
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=300, unique=True, editable=False)
    author = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, related_name="blog_posts"
    )
    body = models.TextField()

    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default="draft"
    )

    class Meta:
        ordering = ("-publish",)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)
        pass 

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={"slug": self.slug})
    

I4G005448SK2_src/blog/views.py
from django.urls import reverse_lazy
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from blog.models import Post 


# from django.contrib.auth.models import Post
# from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# from I4G005448SK2_src.blog.models import Post


# creating classes
class PostListView(ListView):
    model = Post
    template_name = 'blog/post_list.html'
    # context_object_name = 'blog'
    paginate_by = 3
    queryset: Post.objects.all()

    # def get_queryset(self):
    #     return super().queryset().filter(STATUS = 'Published')
    # paginate_by: 3
        


class PostCreateView(CreateView):
    model = Post
    fields = '__all__'
    success_url = reverse_lazy('blog:all')


class PostDetailView(DetailView):
    model = Post
    


class PostUpdateView(UpdateView):
    model = Post
    fields = '__all__'
    success_url = reverse_lazy('blog:all')


class PostDeleteView(DeleteView):
    model = Post
    fields = '__all__'
    success_url = reverse_lazy('blog:all')

I4G005448SK2_src/blog/templates/base.html
<!DOCTYPE HTML>
<html lang="en">

<head>

<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">


{% block title %}
    {% if title %}
        <title>{{title}} | My Blog ✏</title> 
    {% else %}
        <title>My Blog Posts 📝</title>
    {% endif %}
{% endblock title %}

{% block head %}
{% endblock head %}
    
</head>

<body>

<div class="container-fluid">
    
    <!-- NAVIGATION BAR -->


    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="d-flex justify-content-between px-5 mx-auto" style="width: 80%;">
            <span class="navbar-text text-white">DJANGO C.R.U.D.</span>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link active" href="{% url 'blog:all' %}">Posts</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link active" href="https://zuri.team/" target="_blank">Checkout Zuri</a>
                </li>
            </ul>
        </div>
    </nav>

    <!-- END OF NAVIGATION BAR -->

</div>

{% block content %}
{% endblock content %}


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>

</body>

</html>

I4G005448SK2_src/blog/templates/blog/post_confirm_delete.html
{% extends "base.html" %}

{% block content %}

{% url 'blog:all' as list_all %}

<div class="container d-flex justify-content-center mt-5" style="width: 50%;">
    <div class="col mt-5 text-center">
        <h1 class="mb-5">Delete Film</h1>

        <p class="h5">Are you sure you want to delete the Post:</p>
        <h3 class="my-5">{{ object.title }}</h3>
        <form action="" method="POST">
            {% csrf_token %}
            {% comment %} <input type="submit" value="Confirm">
            <input type="submit" value="Cancel" onclick="window.location='{% url 'blog:all' %}'; return false;"> {% endcomment %}
            <input type="submit" class="btn btn-primary btn-lg" value="Confirm" style="margin-right: 30px; margin-top: 30px;">
            <input type="submit" class="btn btn-danger btn-lg" style="margin-top: 30px;" onclick="window.location='{{list_all}}'; return false;" value="Cancel">
        </form>
    </div>
</div>

{% endblock %}

I4G005448SK2_src/blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-5" style="width: 70%;">
    <div class="col">
        <h1 class="text-center">{{object.title}}</h1>
        <hr>
        <div class="d-flex justify-content-center">
            <section>
                <p>{{object.body|linebreaks}}</p>
            </section>
        </div>
        <div>Author: <strong>{{object.author}}<strong><br>
            <small>Published: {{object.publish|date:"D, d M, y"}}</small>
            <small>Created: {{object.create|date:"D, d M, y"}}
        </div>
        <div class="d-flex justify-content-center">
            <a href="{% url 'blog:all' %}" class="d-block btn btn-primary btn-lg my-5">BACK</a>
        </div>
    </div>
</div>

{% endblock  %}

I4G005448SK2_src/blog/templates/blog/post_form.html
{% extends "base.html" %}

{% block content %}

<!-- BOOTSTRAP FORM -->

<div class="container d-flex justify-content-center mt-5" style="width: 25%;">
    <div class="col mt-5">
        <form action="" method="post">
            {% csrf_token %}
            <table class="table">
                {{form.as_table}}
            </table>
            <div class="container d-flex justify-content-center" style="width: 10%;">
                <input type="submit" class="btn btn-primary btn-lg" value="Submit" style="margin-right: 30px; margin-top: 30px;">
                <input type="submit" class="btn btn-danger btn-lg" style="margin-top: 30px;" onclick="window.location='{% url 'blog:all' %}'; return false;" value="Cancel">
            </div>    
        </form> 

    </div>
</div>

<!-- END BOOTSTRAP FORM -->

{% endblock %}

I4G005448SK2_src/blog/templates/blog/post_list.html
{% extends 'base.html' %}

{% block content %}
{% for film in film_list %}
    {% for colname in film.column_set.all  %}
        <p>{{colname}}</p>
    {% endfor %}
{% endfor %}


<div class="container d-flex mt-5" style="width: 70%;">
    <div class="col">
        <h1 class="text-center">My Films</h1>
        <table class="table table-striped mt-5">
            <thead>
                <tr>
                    {% comment %} <th>#</th> {% endcomment %}
                    <th class="text-center" scope="col">Title</th>
                    <th class="text-center" scope="col">Author</th>
                    <th class="text-center" scope="col">Summary</th>
                    <th class="text-center" scope="col">Status</th>
                    <th class="text-center" scope="col">Date Published</th>
                    <th class="text-center" scope="col">Date Created</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            
                {% for post in post_list %}
                <tr>
                    {% comment %} <th scope="row">{{forloop.counter}}</th> {% endcomment %}
                    <td class="ml-5"><a href="{{post.get_absolute_url}}">{{post.title}}</a></td>
                    <td class="text-center">{{post.author}}</td>
                    <td class="text-center">{{post.body|truncatewords:30|linebreaks}}</td>
                    <td class="text-center">{{post.status}}</td>
                    <td class="text-center">{{post.publish|date:"D, d M, y"}}</td>
                    <td class="text-center">{{post.created|date:"D, d M, y"}}</td>
                    <td><a href="{% url 'blog:post_update' post.slug %} ">Update</a></td>
                    <td><a href="{% url 'blog:post_delete' post.slug %}">Delete</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>    

        {% if is_paginated %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
             <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                {% else %}
             <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
            {% else %}
            <li><a href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
            {% else %}
                <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
        </ul>
        {% endif %}


        <div class="d-flex justify-content-center">
            <a href="{% url 'blog:post_create' %}" class="d-block btn btn-primary btn-lg my-5">Add New</a>
        </div>
    </div>
        
</div>

{% endblock content %}